# Generated by Django 6.0 on 2025-12-24 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('uiux', 'UI/UX Design'), ('brand', 'Brand Identity'), ('graphic', 'Graphic Design'), ('other', 'Something Else')], max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline', models.CharField(choices=[('urgent', 'Urgent (1-2 weeks)'), ('standard', 'Standard (3-6 weeks)'), ('flexible', 'Flexible (6+ weeks)')], max_length=20)),
                ('reference_links', models.TextField(blank=True, null=True)),
                ('heard_from', models.CharField(blank=True, choices=[('search', 'Search Engine'), ('social', 'Social Media'), ('referral', 'Referral'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('attached_files', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('accepted', 'Project Accepted'), ('rejected', 'Project Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
